# Generated by Django 5.2 on 2025-05-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('anhosExperiencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DoctoresEspecialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctoresEspecialidades', to='api.doctores')),
                ('Especialidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctoresEspecialidades', to='api.especialidades')),
            ],
        ),
        migrations.AddField(
            model_name='doctores',
            name='Especialidades',
            field=models.ManyToManyField(related_name='doctores', through='api.DoctoresEspecialidades', to='api.especialidades'),
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=100)),
                ('Doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Citas', to='api.doctores')),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Citas', to='api.pacientes')),
            ],
        ),
    ]
