# Generated by Django 5.2 on 2025-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='edad',
            field=models.CharField(max_length=10),
        ),
    ]
